#!/usr/bin/env zsh

set +o allexport
set -o errexit
set -o nounset
set -o pipefail

chores::usage() {
    echo "Usage: chores [sugarcrm]" 1>&2
    exit ${1:-0}
}

if [[ "$#" -eq 0 ]]; then
    chores::usage 1
fi

# Source all files in lib/. Take into consideration that the binary may be
# linked.
CHORES_LIB=${0:A:h}/lib
for file in $(find $CHORES_LIB); do
    if [[ -f "${file}" ]]; then
        source "${file}"
    fi
done

case $1 in
sugarcrm)
    shift
    chores::sugarcrm "$@"
    ;;
*)
    chores::usage 1
    ;;
esac
