#!/usr/bin/env zsh

set +o allexport
set -o errexit
set -o nounset
set -o pipefail

doit::usage() {
    echo "Usage: doit [sugarcrm]" 1>&2
    exit ${1:-0}
}

if [[ "$#" -eq 0 ]]; then
    doit::usage 1
fi

# Source all files in lib/. Take into consideration that the binary may be
# linked.
DOIT_LIB=${0:A:h}/lib
for file in $(find $DOIT_LIB); do
    if [[ -f "${file}" ]]; then
        source "${file}"
    fi
done

case $1 in
sugarcrm)
    shift
    doit::sugarcrm "$@"
    ;;
*)
    doit::usage 1
    ;;
esac
