#!/usr/bin/env zsh

set -o errexit
set -o nounset
set -o pipefail

shortcuts::usage() {
    echo "Usage: shortcuts [sugarconnect]" 1>&2
    exit ${1:-0}
}

if [[ "$#" -eq 0 ]]; then
    shortcuts::usage 1
fi

# Globals.
MULTIVERSE="${HOME}/github.com/sugarcrm/multiverse"

# Source all files in lib/.
for file in $(find ./lib); do
    if [[ -f "${file}" ]]; then
        source "${file}"
    fi
done

case $1 in
sugarconnect)
    shift
    shortcuts::sugarconnect "$@"
    ;;
*)
    shortcuts::usage 1
    ;;
esac
